name: cafe5_shop_mobile_client
description: miura

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+16

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.2
  path: ^1.8.1
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.1.5
  flutter_local_notifications: ^18.0.0
  package_info_plus: ^8.1.0
  flutter_launcher_icons: ^0.14.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  rxdart: ^0.28.0
  flutter_bloc: ^8.1.2
  path_provider: ^2.0.14
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  carousel_slider: ^5.0.0
  table_calendar: ^3.0.8
  flutter_localization: ^0.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter_icons:
    android: "launcher_icon"
    ios: true
    remove_alpha_ios: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/

